name: CI

on: [push]

permissions:
  contents: read

jobs:
  test_suite:
    name: Test on php ${{ matrix.php_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php_version: ["8.2"]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, yaml, pdo_mysql, openssl, curl
          coverage: xdebug
          tools: composer

      - name: Install dependencies
        run: composer install

      - name: Run coverage report
        run: ./vendor/bin/phpunit --coverage-text="phpunit_coverage.txt"

      - name: Coverage summary
        run: cat phpunit_coverage.txt >> $GITHUB_STEP_SUMMARY